export const APP_ROUTES = {
  login: "/login",
  welcome: "/welcome",
  dashboard: "/dashboard",
  newProject: "/new-project",
  projectInfo: "/new-project/info",
  environment: "/new-project/environment",
  projectPath: "/new-project/path",
  solarSelect: "/new-project/solar/select",
  solarOffgrid: "/new-project/solar/offgrid",
  solarHybrid: "/new-project/solar/hybrid",
  solarOngrid: "/new-project/solar/ongrid",
  emergency: "/new-project/emergency",
  projects: "/projects",
  readyScenarios: "/scenarios",
  aiAssistant: "/assistant",
  userFeedback: "/feedback",
  education: "/education",
  contact: "/contact",
  output: "/new-project/summary",
  auth: "/login",
};
