-- SHIL Auth Security V3 - Production RLS baseline
-- Run in Supabase SQL Editor after reviewing table/column names against your project.
-- This migration assumes public.profiles(id uuid PK -> auth.users.id, role text, status text).

begin;

-- Core tables used by the V3 browser client. Existing compatible tables are preserved.
create table if not exists public.shil_records (
  id bigint generated by default as identity primary key,
  base_key text not null,
  record_id text not null,
  user_id text not null,
  user_role text not null default 'user',
  user_login text not null default '',
  status text not null default 'open',
  record jsonb not null default '{}'::jsonb,
  owner_auth_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (base_key, record_id)
);

create table if not exists public.shil_admin_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.shil_admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id text not null,
  actor_auth_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null default 'admin',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Helper functions execute as owner and only return authorization facts.
create or replace function public.shil_current_access_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select case
    when p.status = 'approved' and lower(coalesce(p.role, 'viewer')) = 'owner' then 'super_admin'
    else lower(coalesce(p.role, 'viewer'))
  end
  from public.profiles p
  where p.id = auth.uid()
  limit 1;
$$;

create or replace function public.shil_is_approved()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.status = 'approved'
  );
$$;

create or replace function public.shil_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.shil_is_approved()
    and public.shil_current_access_role() in ('admin','super_admin');
$$;

create or replace function public.shil_is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.shil_is_approved()
    and public.shil_current_access_role() = 'super_admin';
$$;

revoke all on function public.shil_current_access_role() from public;
revoke all on function public.shil_is_approved() from public;
revoke all on function public.shil_is_admin() from public;
revoke all on function public.shil_is_super_admin() from public;
grant execute on function public.shil_current_access_role() to authenticated;
grant execute on function public.shil_is_approved() to authenticated;
grant execute on function public.shil_is_admin() to authenticated;
grant execute on function public.shil_is_super_admin() to authenticated;

-- Profiles: users read self; admins read all. Only admins can manage status.
-- Only super_admin can grant/revoke admin/super_admin roles.
alter table public.profiles enable row level security;

drop policy if exists shil_profiles_read_self_or_admin on public.profiles;
create policy shil_profiles_read_self_or_admin
on public.profiles for select to authenticated
using (id = auth.uid() or public.shil_is_admin());

drop policy if exists shil_profiles_update_self_basic on public.profiles;
create policy shil_profiles_update_self_basic
on public.profiles for update to authenticated
using (id = auth.uid() and public.shil_is_approved())
with check (
  id = auth.uid()
  and status = (select p.status from public.profiles p where p.id = auth.uid())
  and role = (select p.role from public.profiles p where p.id = auth.uid())
);

drop policy if exists shil_profiles_admin_update on public.profiles;
create policy shil_profiles_admin_update
on public.profiles for update to authenticated
using (public.shil_is_admin())
with check (
  public.shil_is_admin()
  and (
    public.shil_is_super_admin()
    or lower(coalesce(role,'viewer')) not in ('admin','super_admin','owner')
  )
);

-- Operational records: owner can CRUD own rows; approved admins can inspect/manage all.
alter table if exists public.shil_records enable row level security;

drop policy if exists shil_records_select on public.shil_records;
create policy shil_records_select
on public.shil_records for select to authenticated
using (owner_auth_id = auth.uid() or public.shil_is_admin());

drop policy if exists shil_records_insert on public.shil_records;
create policy shil_records_insert
on public.shil_records for insert to authenticated
with check (public.shil_is_approved() and owner_auth_id = auth.uid());

drop policy if exists shil_records_update on public.shil_records;
create policy shil_records_update
on public.shil_records for update to authenticated
using (owner_auth_id = auth.uid() or public.shil_is_admin())
with check (owner_auth_id = auth.uid() or public.shil_is_admin());

drop policy if exists shil_records_delete on public.shil_records;
create policy shil_records_delete
on public.shil_records for delete to authenticated
using (owner_auth_id = auth.uid() or public.shil_is_admin());

-- Admin settings are admin-only.
alter table if exists public.shil_admin_settings enable row level security;
drop policy if exists shil_admin_settings_admin_all on public.shil_admin_settings;
create policy shil_admin_settings_admin_all
on public.shil_admin_settings for all to authenticated
using (public.shil_is_admin())
with check (public.shil_is_admin());

-- Audit log: clients can INSERT their own admin action, but cannot update/delete.
-- Admins may read; audit rows should be immutable from browser clients.
alter table if exists public.shil_admin_audit_log enable row level security;
drop policy if exists shil_audit_admin_read on public.shil_admin_audit_log;
create policy shil_audit_admin_read
on public.shil_admin_audit_log for select to authenticated
using (public.shil_is_admin());

drop policy if exists shil_audit_admin_insert on public.shil_admin_audit_log;
create policy shil_audit_admin_insert
on public.shil_admin_audit_log for insert to authenticated
with check (public.shil_is_admin() and actor_auth_id = auth.uid());

-- Explicitly remove browser-side UPDATE/DELETE capability on audit table.
revoke update, delete on public.shil_admin_audit_log from authenticated;

grant select on public.profiles to authenticated;
grant update on public.profiles to authenticated;
grant select, insert, update, delete on public.shil_records to authenticated;
grant select, insert, update, delete on public.shil_admin_settings to authenticated;
grant select, insert on public.shil_admin_audit_log to authenticated;

commit;
