create table if not exists public.shil_user_directory (
  user_id text primary key,
  email text,
  full_name text,
  phone text,
  company text,
  auth_type text not null default 'email',
  role text not null default 'user',
  status text not null default 'active',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  login_count integer not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.shil_login_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  email text,
  full_name text,
  phone text,
  company text,
  auth_type text not null default 'email',
  created_at timestamptz not null default now()
);

alter table public.shil_user_directory enable row level security;
alter table public.shil_login_events enable row level security;

drop policy if exists "shil_admin_read_user_directory" on public.shil_user_directory;
create policy "shil_admin_read_user_directory"
on public.shil_user_directory for select to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin' and p.status = 'approved'));

drop policy if exists "shil_admin_read_login_events" on public.shil_login_events;
create policy "shil_admin_read_login_events"
on public.shil_login_events for select to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin' and p.status = 'approved'));

grant select on public.shil_user_directory to authenticated;
grant select on public.shil_login_events to authenticated;
