-- SHIL V3.3 Security & Audit Center
-- Run after V3 and V3.2 migrations. Test on staging first.
-- Tracks SHIL application sessions, not raw Supabase refresh-token sessions.

create table if not exists public.shil_security_sessions (
  session_id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  login text not null default '',
  role text not null default 'viewer',
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  end_reason text,
  revoked_at timestamptz,
  revoked_by uuid references auth.users(id)
);

create table if not exists public.shil_security_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists shil_security_sessions_user_idx on public.shil_security_sessions(user_id, last_seen_at desc);
create index if not exists shil_security_sessions_active_idx on public.shil_security_sessions(last_seen_at desc) where ended_at is null;
create index if not exists shil_security_events_user_idx on public.shil_security_events(user_id, created_at desc);
create index if not exists shil_security_events_type_idx on public.shil_security_events(event_type, created_at desc);

alter table public.shil_security_sessions enable row level security;
alter table public.shil_security_events enable row level security;

create or replace function public.shil_is_security_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.status = 'approved'
      and lower(coalesce(p.role,'')) in ('admin','super_admin','owner')
  );
$$;

create or replace function public.shil_record_security_event(p_event_type text, p_payload jsonb default '{}'::jsonb, p_session_id text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  insert into public.shil_security_events(user_id,session_id,event_type,payload)
  values (auth.uid(), p_session_id, left(coalesce(p_event_type,'unknown'),80), coalesce(p_payload,'{}'::jsonb));
end;
$$;

create or replace function public.shil_register_security_session(p_session_id text, p_login text, p_role text, p_user_agent text default '')
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  insert into public.shil_security_sessions(session_id,user_id,login,role,user_agent,last_seen_at,ended_at,end_reason,revoked_at,revoked_by)
  values (p_session_id,auth.uid(),left(coalesce(p_login,''),320),left(coalesce(p_role,'viewer'),40),left(coalesce(p_user_agent,''),500),now(),null,null,null,null)
  on conflict (session_id) do update set
    last_seen_at=now(), login=excluded.login, role=excluded.role, user_agent=excluded.user_agent
  where public.shil_security_sessions.user_id=auth.uid();
end;
$$;

create or replace function public.shil_touch_security_session(p_session_id text)
returns table(revoked_at timestamptz) language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  update public.shil_security_sessions s set last_seen_at=now()
  where s.session_id=p_session_id and s.user_id=auth.uid() and s.ended_at is null;
  return query select s.revoked_at from public.shil_security_sessions s where s.session_id=p_session_id and s.user_id=auth.uid();
end;
$$;

create or replace function public.shil_end_security_session(p_session_id text, p_reason text default 'logout')
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  update public.shil_security_sessions set ended_at=coalesce(ended_at,now()), end_reason=left(coalesce(p_reason,'logout'),60)
  where session_id=p_session_id and user_id=auth.uid();
end;
$$;

create or replace function public.shil_revoke_security_session(p_session_id text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.shil_is_security_admin() then raise exception 'admin access required'; end if;
  update public.shil_security_sessions set revoked_at=coalesce(revoked_at,now()), revoked_by=auth.uid()
  where session_id=p_session_id and user_id<>auth.uid();
end;
$$;

revoke all on function public.shil_record_security_event(text,jsonb,text) from public;
revoke all on function public.shil_register_security_session(text,text,text,text) from public;
revoke all on function public.shil_touch_security_session(text) from public;
revoke all on function public.shil_end_security_session(text,text) from public;
revoke all on function public.shil_revoke_security_session(text) from public;
grant execute on function public.shil_record_security_event(text,jsonb,text) to anon, authenticated;
grant execute on function public.shil_register_security_session(text,text,text,text) to authenticated;
grant execute on function public.shil_touch_security_session(text) to authenticated;
grant execute on function public.shil_end_security_session(text,text) to authenticated;
grant execute on function public.shil_revoke_security_session(text) to authenticated;

-- Only approved admins may browse the security tables. Mutations go through RPCs above.
drop policy if exists shil_security_sessions_admin_select on public.shil_security_sessions;
create policy shil_security_sessions_admin_select on public.shil_security_sessions for select to authenticated
using (public.shil_is_security_admin() or user_id=auth.uid());

drop policy if exists shil_security_events_admin_select on public.shil_security_events;
create policy shil_security_events_admin_select on public.shil_security_events for select to authenticated
using (public.shil_is_security_admin());
