import { runEngineeringDesign } from './src/domain/engine/orchestrator/runEngineeringDesign.js';
const common = { projectTitle: 'سناریوی تست', loadVoltage: 220, powerFactor: 0.9, batteryType: 'LFP', batteryRoundTripEfficiency: 0.95, dod: 0.8, inverterEfficiency: 0.93, cableLossFactor: 0.97, controllerEfficiency: 0.95, panelLossFactor: 0.9, shadingFactor: 0.95, dustFactor: 0.96, averageTemperature: 30, minTemperature: 0, maxTemperature: 45, sunHours: 5, panelWatt: 585, panelVoc: 53.1, panelVmp: 44.8, panelIsc: 13.9, panelTempCoeffVoc: 0.0024, panelPowerTempCoeffPercentPerC: 0.35, panelVmpTempCoeffPercentPerC: 0.29, controllerMaxVoc: 500, maxPvVocV: 500, mpptMinVoltage: 120, mpptMaxVoltage: 450, mpptStartupVoltage: 120, mpptCount: 2, maxStringsPerMppt: 2, maxInputCurrentPerMpptA: 30, maxShortCircuitCurrentPerMpptA: 40, maxPvPowerW: 16000, maxPvPowerPerMpptW: 8000, inverterAcPowerW: 10000, systemVoltage: 48, batteryUnitVoltage: 51.2, batteryUnitAh: 100, dcCableLength: 20, batteryCableLength: 2, acCableLength: 20, dcVoltageDropLimit: 3, batteryVoltageDropLimit: 2, acVoltageDropLimit: 3, designFactor: 1.2 };
const cases = [
 { name:'PV سبک', form:{...common, systemType:'offgrid', calculationMode:'daily_energy', dailyEnergyKwh:1.5, backupHours:5, daysAutonomy:1, batteryRechargeDays:2 } },
 { name:'PV متوسط', form:{...common, systemType:'offgrid', calculationMode:'daily_energy', dailyEnergyKwh:7, backupHours:6, daysAutonomy:2, batteryUnitAh:100, batteryRechargeDays:2 } },
 { name:'PV سنگین', form:{...common, systemType:'offgrid', calculationMode:'daily_energy', dailyEnergyKwh:35, backupHours:8, daysAutonomy:1, batteryUnitAh:200, inverterAcPowerW:12000, maxPvPowerW:22000, maxPvPowerPerMpptW:11000, maxInputCurrentPerMpptA:30, maxShortCircuitCurrentPerMpptA:40, batteryRechargeDays:2 } },
 { name:'Backup سبک', form:{...common, systemType:'backup', calculationMode:'power', loadPower:100, backupHours:3, systemVoltage:24, batteryUnitVoltage:12, batteryUnitAh:100 } },
 { name:'Backup متوسط', form:{...common, systemType:'backup', calculationMode:'loads', backupHours:4, systemVoltage:48, batteryUnitVoltage:12, batteryUnitAh:150, loadItems:[{name:'روشنایی ضروری', qty:8, power:15, hours:4, powerFactor:.95, coincidenceFactor:1, backupPriority:'critical'}, {name:'یخچال', qty:1, power:180, hours:8, powerFactor:.8, coincidenceFactor:.6, surgeFactor:2, loadType:'motor', backupPriority:'important'}, {name:'مودم و دوربین', qty:1, power:60, hours:24, powerFactor:.95, coincidenceFactor:1, backupPriority:'critical'}] } },
 { name:'Backup سنگین خورشیدی', form:{...common, systemType:'backup', backupWithSolar:true, backupSolarMode:'with_solar', calculationMode:'loads', backupHours:6, systemVoltage:48, batteryUnitVoltage:12, batteryUnitAh:200, batteryRechargeDays:1, maxPvPowerW:10000, loadItems:[{name:'پمپ', qty:1, power:1500, hours:2, powerFactor:.82, coincidenceFactor:1, surgeFactor:3.5, loadType:'motor', backupPriority:'critical'}, {name:'روشنایی', qty:20, power:20, hours:6, powerFactor:.95, coincidenceFactor:1, backupPriority:'critical'}, {name:'سرور', qty:1, power:600, hours:24, powerFactor:.95, coincidenceFactor:1, backupPriority:'important'}] } },
];
for(const c of cases){ const r=runEngineeringDesign(c.form); if(!r.ok){console.log(c.name, r.errors); continue;} const {summary,battery,decision}=r.result; console.log(JSON.stringify({case:c.name,status:summary.designStatus,dailyWh:summary.totalDailyEnergyWh,demandW:summary.demandPowerW,batteryCount:summary.batteryCount,backupHours:summary.realBackupHours,panelCount:summary.panelCount,pvW:summary.pvInstalledPowerW,pvDailyWh:summary.pvDailyProductionWh,mppt:summary.mpptCompatibilityStatus,dcAc:summary.dcAcRatio,decision:decision.overallStatus,energySizing:decision.energySizing,priority:battery.backupPriorityCoverage?.map(x=>({level:x.level,h:x.estimatedBackupHours,status:x.status}))})); }
