import { runEngineeringDesign } from './src/domain/engine/orchestrator/runEngineeringDesign.js';
const common={calculationMode:'loads', loadVoltage:220, powerFactor:0.9, coincidenceFactor:1, designFactor:1.2, surgeFactor:1.5, sunHours:5, systemVoltage:48, batteryType:'LFP', batteryUnitVoltage:51.2, batteryUnitAh:100, dod:0.8, inverterEfficiency:0.93, controllerEfficiency:0.95, cableLossFactor:0.97, panelLossFactor:0.9, shadingFactor:0.95, dustFactor:0.96, panelWatt:585, panelVoc:53.1, panelVmp:44.8, panelTempCoeffVoc:0.0024, panelTypeTemperatureFactor:0.29, averageTemperature:30, minTemperature:0, maxTemperature:45, maxPvVocV:500, mpptMinVoltage:60, mpptMaxVoltage:450, mpptStartupVoltage:60, mpptCount:2, maxInputCurrentPerMpptA:100, maxShortCircuitCurrentPerMpptA:125, maxStringsPerMppt:2, roofAreaM2:500};
const cases=[
 {name:'Solar light offgrid', form:{...common, projectTitle:'سبک خورشیدی', systemType:'offgrid', daysAutonomy:1, inverterRatedPowerW:3000, inverterAcPowerW:3000, loadItems:[{name:'روشنایی',qty:6,power:12,hours:6,powerFactor:.95,coincidenceFactor:1},{name:'یخچال کوچک',qty:1,power:120,hours:10,powerFactor:.8,coincidenceFactor:.6,surgeFactor:2.5,loadType:'motor'},{name:'تلویزیون',qty:1,power:80,hours:4,powerFactor:.9,coincidenceFactor:1}]}},
 {name:'Solar medium offgrid', form:{...common, projectTitle:'متوسط خورشیدی', systemType:'offgrid', daysAutonomy:1, inverterRatedPowerW:6000, inverterAcPowerW:6000, loadItems:[{name:'روشنایی',qty:15,power:15,hours:6,powerFactor:.95,coincidenceFactor:1},{name:'یخچال',qty:2,power:180,hours:10,powerFactor:.8,coincidenceFactor:.7,surgeFactor:2.5,loadType:'motor'},{name:'پمپ نیم اسب',qty:1,power:750,hours:2,powerFactor:.8,coincidenceFactor:1,surgeFactor:3,loadType:'motor'},{name:'تلویزیون و لپتاپ',qty:3,power:100,hours:5,powerFactor:.9,coincidenceFactor:.8}]}},
 {name:'Solar heavy offgrid', form:{...common, projectTitle:'سنگین خورشیدی', systemType:'offgrid', daysAutonomy:1, inverterRatedPowerW:12000, inverterAcPowerW:12000, mpptCount:2, maxPvPowerW:16000, maxPvPowerPerMpptW:8000, maxInputCurrentPerMpptA:60, maxShortCircuitCurrentPerMpptA:80, batteryUnitAh:200, loadItems:[{name:'روشنایی و اداری',qty:30,power:20,hours:8,powerFactor:.95,coincidenceFactor:.8},{name:'یخچال صنعتی',qty:3,power:500,hours:12,powerFactor:.8,coincidenceFactor:.7,surgeFactor:3,loadType:'motor'},{name:'پمپ آب',qty:2,power:1500,hours:3,powerFactor:.82,coincidenceFactor:.8,surgeFactor:3,loadType:'motor'},{name:'کولر/فن',qty:2,power:1200,hours:6,powerFactor:.85,coincidenceFactor:.8,surgeFactor:2.5,loadType:'motor'}]}},
 {name:'Backup light', form:{...common, projectTitle:'سبک اضطراری', systemType:'backup', backupHours:3, systemVoltage:24, batteryUnitVoltage:12, batteryUnitAh:100, inverterRatedPowerW:1000, inverterAcPowerW:1000, loadItems:[{name:'روشنایی ضروری',qty:8,power:10,hours:3,powerFactor:.95,coincidenceFactor:1},{name:'مودم',qty:1,power:20,hours:3,powerFactor:.9,coincidenceFactor:1}]}},
 {name:'Backup medium', form:{...common, projectTitle:'متوسط اضطراری', systemType:'backup', backupHours:4, systemVoltage:48, batteryUnitVoltage:12, batteryUnitAh:150, inverterRatedPowerW:3000, inverterAcPowerW:3000, loadItems:[{name:'روشنایی',qty:12,power:12,hours:4,powerFactor:.95,coincidenceFactor:1},{name:'یخچال',qty:1,power:180,hours:4,powerFactor:.8,coincidenceFactor:.8,surgeFactor:2.5,loadType:'motor'},{name:'کامپیوتر',qty:2,power:150,hours:4,powerFactor:.9,coincidenceFactor:1}]}},
 {name:'Backup heavy', form:{...common, projectTitle:'سنگین اضطراری', systemType:'backup', backupHours:6, systemVoltage:48, batteryUnitVoltage:12, batteryUnitAh:200, inverterRatedPowerW:8000, inverterAcPowerW:8000, loadItems:[{name:'روشنایی',qty:40,power:15,hours:6,powerFactor:.95,coincidenceFactor:.9},{name:'سرور/IT',qty:5,power:300,hours:6,powerFactor:.9,coincidenceFactor:1},{name:'پمپ',qty:1,power:1500,hours:2,powerFactor:.82,coincidenceFactor:1,surgeFactor:3,loadType:'motor'},{name:'یخچال/فریزر',qty:3,power:250,hours:6,powerFactor:.8,coincidenceFactor:.7,surgeFactor:2.5,loadType:'motor'}]}}
];
for (const c of cases){
 const r=runEngineeringDesign(c.form);
 if(!r.ok){console.log(c.name,'ERR',r.errors); continue}
 const s=r.result.summary; const pv=r.result.pv; const b=r.result.battery; const inv=r.result.inverter; const ind=r.result.industrial;
 console.log(JSON.stringify({case:c.name,status:s.designStatus, decision:s.decisionStatus, loadW:s.demandPowerW, surgeW:s.inverterSurgePowerW, dailyWh:s.totalDailyEnergyWh, invW:s.inverterPowerW, invVA:s.inverterPowerVA, battAh:s.batteryAh, battBankAh:b.bankNominalAh, battUnits:s.batteryCount, usableWh:b.usableBatteryWh, backupH:s.batteryBackupHours, backupPeakH:s.batteryBackupHoursAtPeak, pvPanels:s.panelCount, pvW:s.pvInstalledPowerW, pvDaily:s.pvDailyProductionWh, pvCoverage:ind.pvCoverageRatio, worstMonth:pv?.worstMonthDailyProductionWh, series:pv?.panelSeriesCount, strings:pv?.panelParallelCount, mpptStatus:s.mpptCompatibilityStatus, dcAc:pv?.dcAcRatio, service:s.serviceabilityScore, validation:s.validationScore, actionItems:ind.actionItems, decisions:r.result.decision.decisions.slice(0,3)}, null, 2));
}
