export const SHIL_SOLAR_PANELS = [
  {
    id: "shil-panel-550-n-type-144hc",
    brand: "SHIL",
    title: "SHIL PV Datasheet 550W N-Type 144HC",
    model: "SHIL-N550-144HC",
    engineeringClass: "PV_550_NTYPE_144HC",
    sourceDataBasis: "Exact SHIL engineering datasheet model for calculation bank",
    category: "panel",
    powerW: 550,
    vmp: 41.96,
    voc: 49.9,
    imp: 13.11,
    isc: 13.9,
    dimensionsMm: { length: 2278, width: 1134, height: 30 },
    weightKg: 28.5,
    areaM2: 2.583,
    efficiency: 0.213,
    cellType: "N-Type Mono crystalline",
    bifacial: false,
    glass: "single-glass",
    maxSystemVoltageV: 1500,
    maxSeriesFuseA: 25,
    tempCoeffPmaxPctC: -0.30,
    tempCoeffVocPctC: -0.25,
    tempCoeffIscPctC: 0.045,
    noctC: 45,
    warranty: { productYears: 15, performanceYears: 30, annualDegradationPct: 0.4 },
    marketSegment: "commercial",
    availability: "active",
    defaultForCalculation: false,
    useCase: "پروژه‌های متوسط و مسیرهای با محدودیت جریان MPPT",
  },
  {
    id: "shil-panel-620-n-type-bifacial-66hd",
    brand: "SHIL",
    title: "SHIL PV Datasheet 620W N-Type Bifacial 66HD",
    model: "SHIL-N620-BF-66HD",
    engineeringClass: "PV_620_NTYPE_66HD_BIFACIAL",
    sourceDataBasis: "Exact SHIL engineering datasheet model; default panel for smart sizing",
    category: "panel",
    powerW: 620,
    vmp: 38.6,
    voc: 46.4,
    imp: 16.06,
    isc: 17.05,
    dimensionsMm: { length: 2384, width: 1303, height: 35 },
    weightKg: 33,
    areaM2: 3.107,
    efficiency: 0.1996,
    cellType: "N-Type Mono crystalline",
    bifacial: true,
    bifacialGainReferencePct: [5, 10],
    glass: "dual-glass",
    maxSystemVoltageV: 1500,
    maxSeriesFuseA: 30,
    tempCoeffPmaxPctC: -0.30,
    tempCoeffVocPctC: -0.25,
    tempCoeffIscPctC: 0.045,
    noctC: 45,
    mechanicalLoadPa: { wind: 2400, snow: 5400 },
    warranty: { productYears: 12, performanceYears: 30, annualDegradationPct: 0.4 },
    marketSegment: "commercial-industrial",
    availability: "active",
    defaultForCalculation: true,
    useCase: "پیش‌فرض هوشمند SHIL برای اکثر پروژه‌های اجرایی؛ تعادل توان، قیمت و کنترل جریان",
  },
  {
    id: "shil-panel-700-n-type-bifacial-66hd",
    brand: "SHIL",
    title: "SHIL PV Datasheet 700W N-Type Bifacial 66HD",
    model: "SHIL-N700-BF-66HD",
    engineeringClass: "PV_700_NTYPE_66HD_BIFACIAL",
    sourceDataBasis: "Exact SHIL engineering datasheet model for high power projects",
    category: "panel",
    powerW: 700,
    vmp: 39.8,
    voc: 47.8,
    imp: 17.59,
    isc: 18.55,
    dimensionsMm: { length: 2384, width: 1303, height: 35 },
    weightKg: 34,
    areaM2: 3.107,
    efficiency: 0.2253,
    cellType: "N-Type Mono crystalline",
    bifacial: true,
    bifacialGainReferencePct: [5, 10],
    glass: "dual-glass",
    maxSystemVoltageV: 1500,
    maxSeriesFuseA: 30,
    tempCoeffPmaxPctC: -0.30,
    tempCoeffVocPctC: -0.25,
    tempCoeffIscPctC: 0.045,
    noctC: 45,
    mechanicalLoadPa: { wind: 2400, snow: 5400 },
    warranty: { productYears: 12, performanceYears: 30, annualDegradationPct: 0.45 },
    marketSegment: "industrial-utility",
    availability: "active",
    defaultForCalculation: false,
    useCase: "پروژه‌های صنعتی و high-power با کنترل دقیق جریان ورودی MPPT",
  },
  {
    id: "shil-panel-740-n-type-66h-monofacial",
    brand: "SHIL",
    title: "SHIL PV Datasheet 740W N-Type 66H Mono-facial",
    model: "SHIL-N740-66H",
    engineeringClass: "PV_740_NTYPE_66H_MONOFACIAL",
    sourceDataBasis: "Exact SHIL engineering datasheet model for utility/high density design",
    category: "panel",
    powerW: 740,
    vmp: 43.0,
    voc: 51.4,
    imp: 17.2,
    isc: 18.2,
    dimensionsMm: { length: 2384, width: 1303, height: 35 },
    weightKg: 33.5,
    areaM2: 3.107,
    efficiency: 0.238,
    cellType: "N-Type Mono crystalline",
    bifacial: false,
    glass: "single-glass",
    maxSystemVoltageV: 1500,
    maxSeriesFuseA: 25,
    tempCoeffPmaxPctC: -0.30,
    tempCoeffVocPctC: -0.25,
    tempCoeffIscPctC: 0.045,
    noctC: 45,
    mechanicalLoadPa: { wind: 2400, snow: 5400 },
    warranty: { productYears: 15, performanceYears: 30, annualDegradationPct: 0.55 },
    marketSegment: "utility",
    availability: "active",
    defaultForCalculation: false,
    useCase: "نیروگاهی و صنعتی با تراکم توان بالا؛ نیازمند کنترل دقیق Voc و جریان MPPT",
  },
  {
    id: "shil-panel-185-mono-36-special",
    brand: "SHIL",
    title: "SHIL PV Datasheet 185W Mono 36-Cell Special",
    model: "SHIL-M185-36",
    engineeringClass: "PV_185_MONO_36_SPECIAL",
    sourceDataBasis: "Exact low-power special-use panel kept for emergency/light-load cases",
    category: "panel",
    powerW: 185,
    vmp: 20.25,
    voc: 24.9,
    imp: 9.15,
    isc: 9.66,
    dimensionsMm: { length: 1480, width: 680, height: 30 },
    areaM2: 1.0064,
    efficiency: 0.184,
    cellType: "Mono PERC",
    bifacial: false,
    glass: "single-glass",
    maxSystemVoltageV: 1000,
    maxSeriesFuseA: 10,
    tempCoeffPmaxPctC: -0.39,
    tempCoeffVocPctC: -0.30,
    tempCoeffIscPctC: 0.045,
    noctC: 45,
    warranty: { productYears: 15, performanceYears: 25 },
    marketSegment: "special-low-power",
    availability: "special",
    defaultForCalculation: false,
    useCase: "فقط برای سیستم‌های سبک، روشنایی، UPS کوچک و پروژه‌های کم‌مصرف",
  },
];

const inverter = (cfg) => ({
  brand: "SHIL",
  waveform: "Pure Sine Wave",
  batterySupported: ["Lead Acid", "Lithium", "LiFePO4"],
  communication: ["CAN", "RS485", "RS232", "WiFi"],
  efficiency: 0.93,
  maxDcVoltage: cfg.maxPvVocV || 500,
  maxPvVoc: cfg.maxPvVocV || 500,
  mpptCount: cfg.mpptCount || 1,
  outputVoltage: cfg.outputVoltage || 230,
  outputFrequency: 50,
  parallelCapable: Boolean(cfg.parallelCapable),
  ...cfg,
  id: cfg.id || `shil-${cfg.series}-${String(cfg.ratedPowerW).replace(/\D/g, "")}-${cfg.batteryVoltage}v`,
  title: cfg.title || `SHIL ${cfg.series} ${Math.round(cfg.ratedPowerW / 1000)}KW ${cfg.batteryVoltage}V`,
  dcVoltage: cfg.batteryVoltage,
  batteryMinVoltage: cfg.batteryMinVoltage ?? (cfg.batteryVoltage === 12 ? 11 : cfg.batteryVoltage === 24 ? 21.6 : 43.2),
  batteryMaxVoltage: cfg.batteryMaxVoltage ?? (cfg.batteryVoltage === 12 ? 13 : cfg.batteryVoltage === 24 ? 29.2 : 58.4),
  surgePowerW: cfg.surgePowerW || cfg.ratedPowerW * 2,
  maxPvPowerW: cfg.maxPvPowerW || Math.round(cfg.ratedPowerW * 1.3),
});

export const SHIL_SOLAR_INVERTERS = [
  inverter({ id: "shil-si-1-6kw-12v", series: "SI", model: "SI 1.6KW", type: "Off Grid", title: "SHIL SI 1.6KW 12V", ratedPowerW: 1600, batteryVoltage: 12, batteryMinVoltage: 11, batteryMaxVoltage: 13, mpptMinV: 30, mpptMaxV: 450, maxPvVocV: 500, maxPvPowerW: 2200, maxPvInputCurrentA: 18, parallelCapable: false, note: "طبق اصلاح نهایی: بانک باتری 12V با بازه 11 تا 13 ولت." }),
  inverter({ id: "shil-si-3-2kw-24v", series: "SI", model: "SI 3.2KW", type: "Off Grid", title: "SHIL SI 3.2KW 24V", ratedPowerW: 3200, batteryVoltage: 24, mpptMinV: 30, mpptMaxV: 450, maxPvVocV: 500, maxPvPowerW: 4200, maxPvInputCurrentA: 22, parallelCapable: false }),
  inverter({ id: "shil-si-4kw-24v", series: "SI", model: "SI 4KW", type: "Off Grid", title: "SHIL SI 4KW 24V", ratedPowerW: 4000, batteryVoltage: 24, mpptMinV: 60, mpptMaxV: 450, maxPvVocV: 500, maxPvPowerW: 5200, maxPvInputCurrentA: 27, parallelCapable: false }),
  inverter({ id: "shil-si-6kw-48v", series: "SI", model: "SI 6KW", type: "Off Grid", title: "SHIL SI 6KW 48V", ratedPowerW: 6000, batteryVoltage: 48, mpptMinV: 60, mpptMaxV: 450, maxPvVocV: 500, maxPvPowerW: 8000, maxPvInputCurrentA: 27, parallelCapable: true }),
  inverter({ id: "shil-hi-4kw-48v", series: "HI", model: "HI 4KW", type: "Hybrid", title: "SHIL HI 4KW 48V Hybrid All In One", ratedPowerW: 4000, batteryVoltage: 48, mpptMinV: 60, mpptMaxV: 450, maxPvVocV: 500, maxPvPowerW: 5200, maxPvInputCurrentA: 27, mpptCount: 1, parallelCapable: true }),
  inverter({ id: "shil-hi-6kw-48v", series: "HI", model: "HI 6KW", type: "Hybrid", title: "SHIL HI 6KW 48V Hybrid All In One", ratedPowerW: 6000, batteryVoltage: 48, mpptMinV: 60, mpptMaxV: 450, maxPvVocV: 500, maxPvPowerW: 8000, maxPvInputCurrentA: 27, mpptCount: 1, parallelCapable: true }),
  inverter({ id: "shil-hi2-8kw-48v", series: "HI2", model: "HI2 8KW", type: "Hybrid", title: "SHIL HI2 8KW 48V", ratedPowerW: 8000, batteryVoltage: 48, mpptMinV: 120, mpptMaxV: 500, maxPvVocV: 500, maxPvPowerW: 11000, maxPvInputCurrentA: 30, mpptCount: 2, parallelCapable: true }),
  inverter({ id: "shil-hi2-11kw-48v", series: "HI2", model: "HI2 11KW", type: "Hybrid", title: "SHIL HI2 11KW 48V", ratedPowerW: 11000, batteryVoltage: 48, mpptMinV: 120, mpptMaxV: 500, maxPvVocV: 500, maxPvPowerW: 14500, maxPvInputCurrentA: 32, mpptCount: 2, parallelCapable: true }),
  inverter({ id: "shil-utility-30kw-600v", series: "UTILITY", model: "UTILITY 30KW", type: "On Grid", title: "SHIL Utility 30KW String Inverter", ratedPowerW: 30000, batteryVoltage: 0, noBatteryRequired: true, mpptMinV: 180, mpptMaxV: 850, maxPvVocV: 1000, maxPvPowerW: 39000, maxPvInputCurrentA: 40, mpptCount: 3, parallelCapable: true, outputVoltage: 400 })
];

const lithiumBattery = (cfg) => ({
  brand: "SHIL",
  series: "LiFePO4 Standing Battery Pack",
  chemistry: "LiFePO4",
  bms: true,
  cycleLife: 6000,
  usableDod: 0.9,
  efficiency: 0.94,
  maxChargeCurrentA: 100,
  recommendedChargeCurrentA: 50,
  maxDischargeCurrentA: cfg.maxDischargeCurrentA || 100,
  optionalDischargeCurrentA: 200,
  parallelSupport: 8,
  communication: ["CAN", "RS485", "RS232"],
  ipRating: "IP20",
  ...cfg,
  id: cfg.id || `shil-lfp-${String(cfg.nominalVoltage).replace(".", "-")}-${cfg.capacityAh}`,
  title: cfg.title || `SHIL LiFePO4 ${cfg.nominalVoltage}V ${cfg.capacityAh}Ah`,
  energyWh: Math.round(cfg.nominalVoltage * cfg.capacityAh),
  minVoltage: cfg.minVoltage ?? (cfg.nominalVoltage === 12 ? 11 : cfg.nominalVoltage === 25.6 ? 21.6 : 43.2),
  maxVoltage: cfg.maxVoltage ?? (cfg.nominalVoltage === 12 ? 13 : cfg.nominalVoltage === 25.6 ? 29.2 : 58.4)
});

export const SHIL_LITHIUM_BATTERIES = [
  lithiumBattery({ id: "shil-lfp-12-100", title: "SHIL LiFePO4 12V 100Ah", nominalVoltage: 12, capacityAh: 100, minVoltage: 11, maxVoltage: 13, maxDischargeCurrentA: 100, note: "برای SI 1.6KW و سیستم‌های 12V سبک" }),
  lithiumBattery({ nominalVoltage: 25.6, capacityAh: 100 }),
  lithiumBattery({ nominalVoltage: 25.6, capacityAh: 200 }),
  lithiumBattery({ nominalVoltage: 51.2, capacityAh: 100 }),
  lithiumBattery({ nominalVoltage: 51.2, capacityAh: 150 }),
  lithiumBattery({ nominalVoltage: 51.2, capacityAh: 200, maxDischargeCurrentA: 200 }),
  lithiumBattery({ nominalVoltage: 51.2, capacityAh: 300, maxDischargeCurrentA: 200 })
];

export const SHIL_SOLAR_PROTECTION_BANK = {
  dcMcb: [
    {
      id: "shil-protection-dc-mcb-1000v-1-63a",
      brand: "SHIL",
      title: "SHIL DC MCB Engineering Class 1000V 1-63A",
      model: null,
      engineeringClass: "DC_MCB_1000V_1_63A",
      category: "protection",
      group: "dcMcb",
      deviceType: "DC_MCB",
      side: "PV_DC",
      dc: true,
      ac: false,
      ratedVoltageV: 1000,
      ratedCurrentRangeA: [1, 63],
      poles: [1, 2, 4],
      breakingCapacityKA: 6,
      tripCurve: "C",
      standard: "IEC/EN60947-2",
      ipRating: "IP20",
      maxTerminalMm2: 25,
      ambientC: [-5, 40],
      useCase: "حفاظت رشته‌ها و ورودی‌های PV با جریان پایین تا متوسط",
      sourceDataBasis: "ETEK EKM1-63DC mapped to SHIL engineering bank",
    },
    {
      id: "shil-protection-dc-mcb-1000v-80-125a",
      brand: "SHIL",
      title: "SHIL DC MCB Engineering Class 1000V 80-125A",
      model: null,
      engineeringClass: "DC_MCB_1000V_80_125A",
      category: "protection",
      group: "dcMcb",
      deviceType: "DC_MCB",
      side: "PV_DC",
      dc: true,
      ac: false,
      ratedVoltageV: 1000,
      ratedCurrentRangeA: [80, 125],
      poles: [1, 2, 4],
      breakingCapacityKA: 10,
      tripCurve: "C",
      standard: "IEC/EN60947-2",
      ipRating: "IP20",
      maxTerminalMm2: 35,
      ambientC: [-5, 40],
      useCase: "حفاظت DC با جریان بالاتر از محدوده MCB کوچک",
      sourceDataBasis: "ETEK EKM1-125DC mapped to SHIL engineering bank",
    },
  ],
  dcMccb: [
    {
      id: "shil-protection-dc-mccb-1500v-100-630a",
      brand: "SHIL",
      title: "SHIL DC MCCB Engineering Class 1500V 100-630A",
      model: null,
      engineeringClass: "DC_MCCB_1500V_100_630A",
      category: "protection",
      group: "dcMccb",
      deviceType: "DC_MCCB",
      side: "PV_DC_OR_BATTERY_DC",
      dc: true,
      ac: false,
      ratedVoltageV: 1500,
      ratedCurrentRangeA: [100, 630],
      poles: [2, 3, 4],
      breakingCapacityKA: { dc750: 85, dc1000: 50, dc1200: 35, dc1500: 20 },
      standard: "IEC60947-2",
      ipRating: "Panel mounted",
      useCase: "حفاظت آرایه‌های PV، ورودی‌های باتری یا باس DC صنعتی با جریان بالا",
      sourceDataBasis: "ETEK EKM7DC MCCB 1500V mapped to SHIL engineering bank",
    },
    {
      id: "shil-protection-dc-mccb-1500v-800-1600a",
      brand: "SHIL",
      title: "SHIL DC MCCB Engineering Class 1500V 800-1600A",
      model: null,
      engineeringClass: "DC_MCCB_1500V_800_1600A",
      category: "protection",
      group: "dcMccb",
      deviceType: "DC_MCCB",
      side: "BATTERY_DC_OR_MAIN_DC",
      dc: true,
      ac: false,
      ratedVoltageV: 1500,
      ratedCurrentRangeA: [800, 1600],
      poles: [3, 4],
      breakingCapacityKA: { dc750: 50, dc1000: 30, dc1200: 15, dc1500: 10 },
      standard: "IEC60947-2",
      ipRating: "Panel mounted",
      useCase: "قطع و حفاظت اصلی DC برای پروژه‌های توان بالا",
      sourceDataBasis: "ETEK EKM7DC MCCB 1500V high current mapped to SHIL engineering bank",
    },
  ],
  spd: [
    {
      id: "shil-protection-spd-pv-t2-600-1500v",
      brand: "SHIL",
      title: "SHIL PV SPD Engineering Class Type II 600-1500VDC",
      model: null,
      engineeringClass: "PV_SPD_T2_600_1500VDC",
      category: "protection",
      group: "spd",
      deviceType: "SPD",
      side: "PV_DC",
      dc: true,
      pv: true,
      spdType: "T2",
      ucRangeVdc: [600, 1500],
      poles: [2, 3],
      nominalDischargeCurrentKA: 20,
      maxDischargeCurrentKA: 40,
      responseTimeNs: 25,
      ipRating: "IP20",
      standard: "IEC/EN61643-31",
      useCase: "حفاظت اضافه ولتاژ DC در شرایط عادی ساختمان و تابلو PV",
      sourceDataBasis: "ETEK EKU5-T2-40PV mapped to SHIL engineering bank",
    },
    {
      id: "shil-protection-spd-pv-t1t2-1000-1500v",
      brand: "SHIL",
      title: "SHIL PV SPD Engineering Class Type I+II 1000-1500VDC",
      model: null,
      engineeringClass: "PV_SPD_T1_T2_1000_1500VDC",
      category: "protection",
      group: "spd",
      deviceType: "SPD",
      side: "PV_DC",
      dc: true,
      pv: true,
      spdType: "T1+T2",
      ucRangeVdc: [1000, 1500],
      poles: [3],
      impulseCurrentKA: 6.25,
      nominalDischargeCurrentKA: 20,
      maxDischargeCurrentKA: 40,
      responseTimeNs: 25,
      ipRating: "IP20",
      standard: "IEC/EN61643-31",
      useCase: "مناطق با ریسک صاعقه، پشت‌بام‌های در معرض، پروژه‌های صنعتی و ورودی اصلی PV",
      sourceDataBasis: "ETEK EKU5-T1+T2-40PV mapped to SHIL engineering bank",
    },
  ],
  fuse: [
    {
      id: "shil-protection-pv-fuse-gpv-1000v-2-32a",
      brand: "SHIL",
      title: "SHIL PV Fuse Engineering Class gPV 1000V 2-32A",
      model: null,
      engineeringClass: "PV_FUSE_GPV_1000V_2_32A",
      category: "protection",
      group: "fuse",
      deviceType: "PV_FUSE",
      side: "PV_DC",
      dc: true,
      pv: true,
      fuseClass: "gPV",
      ratedVoltageV: 1000,
      currentRangeA: [2, 32],
      breakingCapacityKA: 50,
      fuseSizesMm: ["10x38"],
      standard: "IEC60269-6",
      useCase: "حفاظت رشته پنل در آرایه‌های موازی تا 1000VDC",
      sourceDataBasis: "ETEK PV fuse link/base 1000V mapped to SHIL engineering bank",
    },
    {
      id: "shil-protection-pv-fuse-gpv-1500v-2-50a",
      brand: "SHIL",
      title: "SHIL PV Fuse Engineering Class gPV 1500V 2-50A",
      model: null,
      engineeringClass: "PV_FUSE_GPV_1500V_2_50A",
      category: "protection",
      group: "fuse",
      deviceType: "PV_FUSE",
      side: "PV_DC",
      dc: true,
      pv: true,
      fuseClass: "gPV",
      ratedVoltageV: 1500,
      currentRangeA: [2, 50],
      breakingCapacityKA: 50,
      fuseSizesMm: ["10x85", "14x85"],
      standard: "IEC60269-6",
      useCase: "حفاظت رشته و کامباینر PV در ولتاژهای بالا تا 1500VDC",
      sourceDataBasis: "ETEK PV fuse link/base 1500V mapped to SHIL engineering bank",
    },
  ],
  isolator: [
    {
      id: "shil-protection-dc-isolator-1500v-32a-ip66",
      brand: "SHIL",
      title: "SHIL DC Isolator Engineering Class 1500V 32A IP66",
      model: null,
      engineeringClass: "DC_ISOLATOR_1500V_32A_IP66",
      category: "protection",
      group: "isolator",
      deviceType: "DC_ISOLATOR",
      side: "PV_DC",
      dc: true,
      pv: true,
      ratedVoltageV: 1500,
      ratedCurrentA: 32,
      poles: [2, 4],
      stringsRecommended: [1, 2, 3, 4],
      ipRating: "IP66",
      standard: "IEC60947-3",
      ambientC: [-40, 85],
      useCase: "کلید قطع DC نزدیک پنل، تابلو DC یا ورودی اینورتر",
      sourceDataBasis: "ETEK EKD6-DB32 / EKD6-EL32R mapped to SHIL engineering bank",
    },
  ],
  loadDisconnector: [
    {
      id: "shil-protection-dc-load-disconnector-1500v-160-800a",
      brand: "SHIL",
      title: "SHIL DC Load Disconnector Engineering Class 1500V 160-800A",
      model: null,
      engineeringClass: "DC_LOAD_DISCONNECTOR_1500V_160_800A",
      category: "protection",
      group: "loadDisconnector",
      deviceType: "DC_LOAD_DISCONNECTOR",
      side: "MAIN_DC",
      dc: true,
      ratedVoltageV: 1500,
      ratedCurrentRangeA: [160, 800],
      poles: [2, 4, 6, 8, 10, 12],
      standard: "IEC60947-3",
      useCase: "قطع بار DC اصلی، باس باتری یا تابلوهای صنعتی DC",
      sourceDataBasis: "ETEK EKHD DC load switch-disconnector mapped to SHIL engineering bank",
    },
  ],
  ac: [
    {
      id: "shil-protection-ac-breaker-230-400v-6-125a",
      brand: "SHIL",
      title: "SHIL AC Breaker Engineering Class 230/400V 6-125A",
      model: null,
      engineeringClass: "AC_BREAKER_230_400V_6_125A",
      category: "protection",
      group: "ac",
      deviceType: "AC_BREAKER",
      side: "AC",
      dc: false,
      ac: true,
      ratedVoltageV: [230, 400],
      ratedCurrentRangeA: [6, 125],
      poles: [1, "1P+N", "3P+N", 4],
      useCase: "حفاظت ورودی/خروجی AC و تابلو مصرف",
    },
    {
      id: "shil-protection-ac-spd-t2-230-400v",
      brand: "SHIL",
      title: "SHIL AC SPD Engineering Class Type II 230/400V",
      model: null,
      engineeringClass: "AC_SPD_T2_230_400V",
      category: "protection",
      group: "ac",
      deviceType: "SPD",
      side: "AC",
      dc: false,
      ac: true,
      spdType: "T2",
      ratedVoltageV: [230, 400],
      poles: ["1P+N", "3P+N"],
      useCase: "حفاظت اضافه ولتاژ سمت AC",
    },
  ],
  battery: [
    {
      id: "shil-protection-battery-fuse-dc-48v-100-300a",
      brand: "SHIL",
      title: "SHIL Battery Fuse Engineering Class 48V 100-300A",
      model: null,
      engineeringClass: "BATTERY_FUSE_48V_100_300A",
      category: "protection",
      group: "battery",
      deviceType: "BATTERY_FUSE",
      side: "BATTERY_DC",
      dc: true,
      ratedVoltageV: 48,
      currentRangeA: [100, 300],
      fuseClass: "NH / MEGA / ANL according to current level",
      useCase: "حفاظت بانک باتری 48V و باس DC باتری",
    },
    {
      id: "shil-protection-battery-isolator-dc-48v-100-300a",
      brand: "SHIL",
      title: "SHIL Battery DC Isolator Engineering Class 48V 100-300A",
      model: null,
      engineeringClass: "BATTERY_ISOLATOR_48V_100_300A",
      category: "protection",
      group: "battery",
      deviceType: "BATTERY_ISOLATOR",
      side: "BATTERY_DC",
      dc: true,
      ratedVoltageV: 48,
      currentRangeA: [100, 300],
      useCase: "قطع دستی و ایمن بانک باتری",
    },
  ],
};

export const SHIL_CABLE_BANK = [
  { id: "pv-6", title: "کابل PV 6mm²", currentA: 45, side: "PV/DC" },
  { id: "pv-10", title: "کابل PV 10mm²", currentA: 65, side: "PV/DC" },
  { id: "dc-25", title: "کابل DC 25mm²", currentA: 110, side: "Battery/DC" },
  { id: "dc-50", title: "کابل DC 50mm²", currentA: 170, side: "Battery/DC" },
  { id: "ac-10", title: "کابل AC 10mm²", currentA: 55, side: "AC" },
  { id: "ac-16", title: "کابل AC 16mm²", currentA: 75, side: "AC" },
  { id: "ac-35", title: "کابل AC 35mm²", currentA: 130, side: "AC" }
];
