export const ERROR_CODES = Object.freeze({
  VALIDATION_FAILED: "VALIDATION_FAILED",
  ENGINE_FAILED: "ENGINE_FAILED",
  ENGINE_NOT_REGISTERED: "ENGINE_NOT_REGISTERED",
  STORAGE_FAILED: "STORAGE_FAILED",
  MIGRATION_FAILED: "MIGRATION_FAILED",
  WORKFLOW_INVALID_STEP: "WORKFLOW_INVALID_STEP",
  REPORT_FAILED: "REPORT_FAILED",
});
