import React, { useMemo } from "react";
import { useNavigate, useParams } from "react-router-dom";
import EngineeringPageShell from "../components/EngineeringPageShell.jsx";
import { ActionBar, DataGrid, DataSection, PageStack, StatusMessage } from "../components/ShilDesignSystem.jsx";
import { approveProjectStep } from "../workflow/projectWorkflow.js";
import { getProjectPath, getSystemSettingsDraft, getSystemSetupHandoff, normalizeProjectDomain, writeJson } from "../engines/projectFlowData.js";
const fmt=(v,d=0)=>v===null||v===undefined||v===""||!Number.isFinite(Number(v))?"—":Number(v).toLocaleString("en-US",{maximumFractionDigits:d}); const name=x=>x?.title||x?.model||x?.name||x?.id||"تجهیز انتخاب‌شده";
function EmergencySummary({handoff,draft}){const d=draft?.designResult||draft?.design||draft||{}; const b=d.battery||{},i=d.inverter||{},l=d.load||handoff?.normalizedLoad||{}; return <>
 <DataSection title="چکیده ورودی محاسبات" meta={handoff?.methodSummary?.title||"برق اضطراری"}><DataGrid rows={[["روش ورود",handoff?.methodSummary?.title||d.sourceMethod||"ورودی بار ضروری"],["توان بار ضروری",`${fmt(l.totalPowerW)} W`],["پیک راه‌اندازی",`${fmt(l.surgePowerW ?? l.totalPowerW)} W`],["ولتاژ خروجی",l.phaseAC==="three"?"380 V سه‌فاز":"220 V تک‌فاز"],["زمان پشتیبانی هدف",`${fmt(d.settings?.backupHours ?? handoff?.autonomy?.backupHours ?? handoff?.autonomy?.hours ?? 3,2)} ساعت`]]}/></DataSection>
 <DataSection title="چکیده تجهیزات و محاسبات" meta="UPS / Battery + Inverter"><DataGrid rows={[["اینورتر پیشنهادی",name(i)],["توان نامی اینورتر",`${fmt(i.ratedPowerW||i.powerW)} W`],["توان طراحی اینورتر",`${fmt(i.designPowerW)} W`],["ولتاژ DC اینورتر",`${fmt(i.dcVoltage ?? i.batteryVoltage ?? 48)} V`],["باتری پیشنهادی",name(b)],["ولتاژ و ظرفیت هر باتری",`${fmt(b.nominalVoltage,1)} V / ${fmt(b.capacityAh)} AH`],["تعداد باتری",`${fmt(b.count)} عدد`],["آرایش باتری",`${fmt(b.seriesCount)} سری × ${fmt(b.parallelCount)} موازی`],["ولتاژ پک",`${fmt(b.packVoltage,1)} V`],["ظرفیت بانک",`${fmt(b.bankCapacityAh,1)} AH`],["انرژی خام بانک",`${fmt(b.grossEnergyKWh,2)} KWH`],["انرژی قابل استفاده",`${fmt(b.usableEnergyKWh,2)} KWH`],["پشتیبانی واقعی",`${fmt(b.runtimeHours,2)} ساعت`],["جریان DC تقریبی",`${fmt(d.electrical?.estimatedDcCurrentA,1)} A`]]}/></DataSection>
 <DataSection title="الزامات اجرایی" meta="حفاظت"><DataGrid rows={[["حفاظت باتری","کلید یا فیوز DC متناسب با جریان طراحی"],["حفاظت خروجی","کلید AC متناسب با توان اینورتر"],["کابل باتری",`متناسب با باس ${fmt(d.electrical?.dcBusVoltage ?? i.dcVoltage ?? 48)} V DC`],["ارت و هم‌بندی","الزامی"],["بای‌پس تعمیراتی","پیشنهاد می‌شود"],["تهویه محل باتری و اینورتر","الزامی مطابق دیتاشیت"]]}/></DataSection></>}
function SolarSummary({handoff,draft}){const d=draft?.designResult||draft?.design||draft||{}; return <DataSection title="چکیده طراحی خورشیدی" meta={handoff?.methodSummary?.title||"خورشیدی"}><DataGrid rows={[["توان مبنا",`${fmt(handoff?.normalizedLoad?.totalPowerW||d?.load?.finalPowerW)} W`],["انرژی روزانه",`${fmt(handoff?.normalizedLoad?.dailyEnergyKWh||d?.load?.finalEnergyKWh,2)} KWH`],["پنل",`${name(d.panel)} × ${fmt(d?.pvArray?.panelCount)} عدد`],["اینورتر",`${name(d.inverter)} × ${fmt(d?.inverter?.count||1)} عدد`],["وضعیت","آماده اجرا"]]}/></DataSection>}
export default function SummaryPage(){const navigate=useNavigate(),params=useParams(); const path=useMemo(()=>getProjectPath(),[]),handoff=useMemo(()=>getSystemSetupHandoff(),[]),draft=useMemo(()=>getSystemSettingsDraft(),[]); const domain=normalizeProjectDomain({...handoff,domain:params.domain||draft?.domain||path.domain}); const run=()=>{const snapshot={domain,handoff,draft,confirmedAt:new Date().toISOString()}; writeJson("shil:summaryDraft",snapshot); writeJson("shil:finalEngineeringOutput",snapshot); approveProjectStep("summary"); navigate(`/new-project/run/${domain}`)}; return <EngineeringPageShell title={domain==="emergency"?"چکیده طراحی برق اضطراری":"چکیده طراحی"} activeStep="summary" backTo={`/new-project/system/${domain}`}><PageStack className="shil-page-scroll shil-summary-page">{domain==="emergency"?<EmergencySummary handoff={handoff} draft={draft}/>:<SolarSummary handoff={handoff} draft={draft}/>} {(draft?.designResult?.warnings||draft?.design?.warnings||[]).map(x=><StatusMessage key={String(x)}>{String(x)}</StatusMessage>)}<DataSection title="آماده اجرا" meta={domain}><p className="shil-muted-line">تمام داده‌های ورودی، محاسبات و تجهیزات انتخابی ثبت شده‌اند.</p><ActionBar><button type="button" className="shil-primary-wide" onClick={run}>اجرای نهایی</button></ActionBar></DataSection></PageStack></EngineeringPageShell>}
